### ISSUE TITLE
可以跑起来，但是访问报错呢

### ISSUE THREAD

**Issue by ahyanhailong** [homerious/angular-ionic-webpack#1]
calendar_pk.min.js?3f2f:1 Uncaught ReferenceError: angular is not defined
    at eval (calendar_pk.min.js?3f2f:1)
    at eval (calendar_pk.min.js?3f2f:1)
    at Object.125 (calendar_pk.c66173f26fd86acaa638.js:16)
    at __webpack_require__ (vendor.bundle.js:713)
    at fn (vendor.bundle.js:118)
    at Object.124 (calendar_pk.c66173f26fd86acaa638.js:8)
    at __webpack_require__ (vendor.bundle.js:713)
    at webpackJsonpCallback (vendor.bundle.js:26)
    at calendar_pk.c66173f26fd86acaa638.js:1
(anonymous) @ calendar_pk.min.js?3f2f:1
(anonymous) @ calendar_pk.min.js?3f2f:1
125 @ calendar_pk.c66173f26fd86acaa638.js:16
__webpack_require__ @ vendor.bundle.js:713
fn @ vendor.bundle.js:118
124 @ calendar_pk.c66173f26fd86acaa638.js:8
__webpack_require__ @ vendor.bundle.js:713
webpackJsonpCallback @ vendor.bundle.js:26
(anonymous) @ calendar_pk.c66173f26fd86acaa638.js:1
ionic-datepicker.bundle.min.js?aa95:1 Uncaught ReferenceError: angular is not defined
    at eval (ionic-datepicker.bundle.min.js?aa95:1)
    at eval (ionic-datepicker.bundle.min.js?aa95:1)
    at Object.123 (datepicker.3e1c2b87f0a7b5e5e2bd.js:16)
    at __webpack_require__ (vendor.bundle.js:713)
    at fn (vendor.bundle.js:118)
    at Object.122 (datepicker.3e1c2b87f0a7b5e5e2bd.js:8)
    at __webpack_require__ (vendor.bundle.js:713)
    at webpackJsonpCallback (vendor.bundle.js:26)
    at datepicker.3e1c2b87f0a7b5e5e2bd.js:1
(anonymous) @ ionic-datepicker.bundle.min.js?aa95:1
(anonymous) @ ionic-datepicker.bundle.min.js?aa95:1
123 @ datepicker.3e1c2b87f0a7b5e5e2bd.js:16
__webpack_require__ @ vendor.bundle.js:713
fn @ vendor.bundle.js:118
122 @ datepicker.3e1c2b87f0a7b5e5e2bd.js:8
__webpack_require__ @ vendor.bundle.js:713
webpackJsonpCallback @ vendor.bundle.js:26
(anonymous) @ datepicker.3e1c2b87f0a7b5e5e2bd.js:1
angular.js?10a4:28348 WARNING: Tried to load angular more than once.
ionic.bundle.js?cd20:41660 WARNING: Tried to load angular more than once.
jquery.js?eedf:3869 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.3%2F%24injector%2Fmodulerr%3Fp0%3Dapp.business%26p1%3DError%253A%2520%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.4.3%252F%2524injector%252Fmodulerr%253Fp0%253Dionic-datepicker%2526p1%253DError%25253A%252520%25255B%252524injector%25253Anomod%25255D%252520http%25253A%25252F%25252Ferrors.angularjs.org%25252F1.4.3%25252F%252524injector%25252Fnomod%25253Fp0%25253Dionic-datepicker%25250A%252520%252520%252520%252520at%252520eval%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A40%25253A416)%25250A%252520%252520%252520%252520at%252520eval%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A58%25253A66)%25250A%252520%252520%252520%252520at%252520a%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A57%25253A109)%25250A%252520%252520%252520%252520at%252520eval%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A57%25253A352)%25250A%252520%252520%252520%252520at%252520eval%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A71%25253A381)%25250A%252520%252520%252520%252520at%252520m%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A41%25253A322)%25250A%252520%252520%252520%252520at%252520g%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A71%25253A229)%25250A%252520%252520%252520%252520at%252520eval%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A71%25253A398)%25250A%252520%252520%252520%252520at%252520m%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A41%25253A322)%25250A%252520%252520%252520%252520at%252520g%252520(webpack-internal%25253A%25252F%25252F%25252F22%25253A71%25253A229)%250A%2520%2520%2520%2520at%2520eval%2520(webpack-internal%253A%252F%252F%252F22%253A40%253A416)%250A%2520%2520%2520%2520at%2520eval%2520(webpack-internal%253A%252F%252F%252F22%253A72%253A154)%250A%2520%2520%2520%2520at%2520m%2520(webpack-internal%253A%252F%252F%252F22%253A41%253A322)%250A%2520%2520%2520%2520at%2520g%2520(webpack-internal%253A%252F%252F%252F22%253A71%253A229)%250A%2520%2520%2520%2520at%2520eval%2520(webpack-internal%253A%252F%252F%252F22%253A71%253A398)%250A%2520%2520%2520%2520at%2520m%2520(webpack-internal%253A%252F%252F%252F22%253A41%253A322)%250A%2520%2520%2520%2520at%2520g%2520(webpack-internal%253A%252F%252F%252F22%253A71%253A229)%250A%2520%2520%2520%2520at%2520eval%2520(webpack-internal%253A%252F%252F%252F22%253A71%253A398)%250A%2520%2520%2520%2520at%2520m%2520(webpack-internal%253A%252F%252F%252F22%253A41%253A322)%250A%2520%2520%2520%2520at%2520g%2520(webpack-internal%253A%252F%252F%252F22%253A71%253A229)%0A%20%20%20%20at%20eval%20(webpack-internal%3A%2F%2F%2F22%3A40%3A416)%0A%20%20%20%20at%20eval%20(webpack-internal%3A%2F%2F%2F22%3A72%3A154)%0A%20%20%20%20at%20m%20(webpack-internal%3A%2F%2F%2F22%3A41%3A322)%0A%20%20%20%20at%20g%20(webpack-internal%3A%2F%2F%2F22%3A71%3A229)%0A%20%20%20%20at%20eval%20(webpack-internal%3A%2F%2F%2F22%3A71%3A398)%0A%20%20%20%20at%20m%20(webpack-internal%3A%2F%2F%2F22%3A41%3A322)%0A%20%20%20%20at%20g%20(webpack-internal%3A%2F%2F%2F22%3A71%3A229)%0A%20%20%20%20at%20eb%20(webpack-internal%3A%2F%2F%2F22%3A74%3A503)%0A%20%20%20%20at%20d%20(webpack-internal%3A%2F%2F%2F22%3A53%3A339)%0A%20%20%20%20at%20Ac%20(webpack-internal%3A%2F%2F%2F22%3A54%3A151)
    at eval (ionic.bundle.min.js?a334:40)
    at eval (ionic.bundle.min.js?a334:72)
    at m (ionic.bundle.min.js?a334:41)
    at g (ionic.bundle.min.js?a334:71)
    at eb (ionic.bundle.min.js?a334:74)
    at d (ionic.bundle.min.js?a334:53)
    at Ac (ionic.bundle.min.js?a334:54)
    at Zd (ionic.bundle.min.js?a334:52)
    at HTMLDocument.eval (ionic.bundle.min.js?a334:323)
    at mightThrow (jquery.js?eedf:3583)
(anonymous) @ ionic.bundle.min.js?a334:40
(anonymous) @ ionic.bundle.min.js?a334:72
m @ ionic.bundle.min.js?a334:41
g @ ionic.bundle.min.js?a334:71
eb @ ionic.bundle.min.js?a334:74
d @ ionic.bundle.min.js?a334:53
Ac @ ionic.bundle.min.js?a334:54
Zd @ ionic.bundle.min.js?a334:52
(anonymous) @ ionic.bundle.min.js?a334:323
mightThrow @ jquery.js?eedf:3583
process @ jquery.js?eedf:3651
setTimeout (async)
jQuery.readyException @ jquery.js?eedf:3868
(anonymous) @ jquery.js?eedf:3888
mightThrow @ jquery.js?eedf:3583
process @ jquery.js?eedf:3651
setTimeout (async)
(anonymous) @ jquery.js?eedf:3689
fire @ jquery.js?eedf:3317
fireWith @ jquery.js?eedf:3447
fire @ jquery.js?eedf:3455
fire @ jquery.js?eedf:3317
fireWith @ jquery.js?eedf:3447
process @ jquery.js?eedf:3671
setTimeout (async)
(anonymous) @ jquery.js?eedf:3689
fire @ jquery.js?eedf:3317
fireWith @ jquery.js?eedf:3447
fire @ jquery.js?eedf:3455
fire @ jquery.js?eedf:3317
fireWith @ jquery.js?eedf:3447
ready @ jquery.js?eedf:3920
completed @ jquery.js?eedf:3930
abstract-xhr.js?c769:132 XHR finished loading: GET "http://localhost:8089/sockjs-node/info?t=1524809354655".
AbstractXHRObject._start @ abstract-xhr.js?c769:132
(anonymous) @ abstract-xhr.js?c769:21
setTimeout (async)
AbstractXHRObject @ abstract-xhr.js?c769:20
XHRLocalObject @ xhr-local.js?19de:8
InfoAjax @ info-ajax.js?7213:19
InfoReceiver._getReceiver @ info-receiver.js?aa33:36
InfoReceiver.doXhr @ info-receiver.js?aa33:56
(anonymous) @ info-receiver.js?aa33:25
setTimeout (async)
InfoReceiver @ info-receiver.js?aa33:24
SockJS @ main.js?8e93:121
socket @ socket.js?e5d0:9
(anonymous) @ client?3e2c:200
(anonymous) @ 10:244
(anonymous) @ vendor.bundle.js:832
__webpack_require__ @ vendor.bundle.js:713
fn @ vendor.bundle.js:118
120 @ jquery.750fb5178cf45e2cea36.js:6
__webpack_require__ @ vendor.bundle.js:713
webpackJsonpCallback @ vendor.bundle.js:26
(anonymous) @ jquery.750fb5178cf45e2cea36.js:1
client?3e2c:77 [WDS] Hot Module Replacement enabled.

**Comment by homerious** [comment]
看报错信息说的是angular未定义，可以检查一下你的angular是不是没有引用到~~
