### ISSUE TITLE
请问入口jq路径 和 生产环境的问题

### ISSUE THREAD

**Issue by magicyangmei** [homerious/angular-ionic-webpack#2]
jq 的入口路径 并没有写 ，只写了jquery: ['jquery'], 这样的配置，请问如何起作用的那？还有就是生产环境里 写的是 
'process.env': {
            NODE_ENV: JSON.stringify("development")
 }
这样不是和开发环境一样了吗？

**Comment by homerious** [comment]
你好，请仔细看`build/webpack.base.config.js`中入口配置，里面就引入了jq.
至于环境的配置那块，首先我这版本里的angularjs貌似并不分辨什么环境，所以这里配置影响不大，然后我这里确实写错了，应该是production，感谢指正。
